#!/bin/bash
# OpenPipeS Auto-Installer
# Generated by OpenPipeS Installer v1.0

echo "🚀 Instalador Automático do OpenPipeS"
echo "======================================"

# Cores para output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Versões específicas (baseado no installer.sh original)
AMASS_VERSION="3.20.0"
DNSRECON_VERSION="1.1.3"
NUCLEI_VERSION="v2"

# Função de log melhorada
log() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

# Detectar arquitetura do sistema
detect_arch() {
    local arch
    arch="$(uname -m)"
    case "$arch" in
        x86_64|amd64) echo "amd64" ;;
        aarch64|arm64) echo "arm64" ;;
        *) echo "amd64" ;; # fallback
    esac
}

# Backup de arquivos existentes
backup_if_exists() {
    local file="$1"
    if [ -e "$file" ]; then
        local stamp
        stamp="$(date +%Y%m%d_%H%M%S)"
        local dest="${file}.backup_${stamp}"
        log "Fazendo backup: '$file' -> '$dest'"
        sudo cp -a "$file" "$dest"
    fi
}

# Verificar se está executando como root para algumas operações
check_sudo() {
    if ! sudo -v; then
        error "Este script precisa de privilégios sudo para algumas operações."
        exit 1
    fi
}

# Atualizar sistema
update_system() {
    log "Atualizando sistema..."
    sudo apt update && sudo apt upgrade -y
}

# Instalar dependências básicas
install_system_deps() {
    log "Instalando dependências básicas do sistema..."
    sudo apt install -y curl jq gawk bind9-host whois fzf git build-essential
}

# Instalar Go (necessário para várias ferramentas)
install_go() {
    if ! command -v go &> /dev/null; then
        log "Instalando Go..."
        wget -q https://go.dev/dl/go1.21.0.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go1.21.0.linux-amd64.tar.gz
        echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
        export PATH=$PATH:/usr/local/go/bin
        rm go1.21.0.linux-amd64.tar.gz
    else
        log "Go já está instalado"
    fi
}

# Instalar Rust (necessário para feroxbuster)
install_rust() {
    if ! command -v cargo &> /dev/null; then
        log "Instalando Rust..."
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source ~/.cargo/env
        echo 'source ~/.cargo/env' >> ~/.bashrc
    else
        log "Rust já está instalado"
    fi
}

# Instalar Amass com versão específica
install_amass() {
    if command -v amass >/dev/null 2>&1; then
        log "Amass já está instalado: $(amass -version 2>&1 | head -n1 || true)"
        return 0
    fi
    
    log "Instalando Amass v${AMASS_VERSION}..."
    local arch
    arch="$(detect_arch)"
    local url="https://github.com/OWASP/Amass/releases/download/v${AMASS_VERSION}/amass_linux_${arch}.zip"
    local tmpdir
    tmpdir="$(mktemp -d)"
    
    curl -L --fail -o "${tmpdir}/amass.zip" "$url"
    unzip -o "${tmpdir}/amass.zip" -d "$tmpdir" >/dev/null 2>&1
    
    if [ -f "${tmpdir}/amass_linux_${arch}/amass" ]; then
        backup_if_exists "/usr/local/bin/amass"
        sudo cp "${tmpdir}/amass_linux_${arch}/amass" "/usr/local/bin/amass"
        sudo chmod +x "/usr/local/bin/amass"
        log "✅ Amass v${AMASS_VERSION} instalado com sucesso"
    else
        error "Arquivo amass não encontrado no download"
        return 1
    fi
    
    rm -rf "$tmpdir"
}

# Instalar DNSRecon com versão específica
install_dnsrecon() {
    if command -v dnsrecon >/dev/null 2>&1; then
        log "DNSRecon já está instalado"
        return 0
    fi
    
    log "Instalando DNSRecon v${DNSRECON_VERSION}..."
    local url="https://github.com/darkoperator/dnsrecon/archive/refs/tags/${DNSRECON_VERSION}.zip"
    local tmpdir
    tmpdir="$(mktemp -d)"
    
    curl -L --fail -o "${tmpdir}/dnsrecon.zip" "$url"
    unzip -o "${tmpdir}/dnsrecon.zip" -d "$tmpdir" >/dev/null 2>&1
    
    local extracted
    extracted="$(find "$tmpdir" -maxdepth 1 -type d -name 'dnsrecon*' | head -n1)"
    
    if [ -n "$extracted" ] && [ -f "${extracted}/dnsrecon.py" ]; then
        backup_if_exists "/usr/local/bin/dnsrecon"
        sudo cp "${extracted}/dnsrecon.py" "/usr/local/bin/dnsrecon"
        sudo chmod +x "/usr/local/bin/dnsrecon"
        log "✅ DNSRecon v${DNSRECON_VERSION} instalado com sucesso"
    else
        error "Arquivo dnsrecon.py não encontrado no download"
        return 1
    fi
    
    rm -rf "$tmpdir"
}

# Instalar ferramentas web com Go
install_web_tools() {
    log "Instalando ferramentas web..."
    
    # Verificar se Go está disponível
    if ! command -v go &> /dev/null; then
        error "Go não está instalado. Instale Go primeiro."
        return 1
    fi
    
    # httpx
    if ! command -v httpx &> /dev/null; then
        log "Instalando httpx..."
        GOBIN=/usr/local/bin go install github.com/projectdiscovery/httpx/cmd/httpx@latest
    fi
    
    # katana
    if ! command -v katana &> /dev/null; then
        log "Instalando katana..."
        GOBIN=/usr/local/bin go install github.com/projectdiscovery/katana/cmd/katana@latest
    fi
    
    # nuclei (versão específica)
    if ! command -v nuclei &> /dev/null; then
        log "Instalando nuclei ${NUCLEI_VERSION}..."
        GOBIN=/usr/local/bin go install github.com/projectdiscovery/nuclei/${NUCLEI_VERSION}/cmd/nuclei@latest
    fi
    
    # feroxbuster (via Go, como no installer.sh original)
    if ! command -v feroxbuster &> /dev/null; then
        log "Instalando feroxbuster..."
        GOBIN=/usr/local/bin go install github.com/epi052/feroxbuster@latest
    fi
    
    # gf (opcional)
    if ! command -v gf &> /dev/null; then
        log "Instalando gf e patterns..."
        go install github.com/tomnomnom/gf@latest
        mkdir -p ~/.gf
        if [ ! -d ~/.gf ] || [ ! -f ~/.gf/README.md ]; then
            git clone https://github.com/1ndianl33t/Gf-Patterns /tmp/gf-patterns
            cp -r /tmp/gf-patterns/* ~/.gf/
            rm -rf /tmp/gf-patterns
        fi
    fi
}

# Instalar nuclei-templates
install_nuclei_templates() {
    log "Instalando nuclei-templates..."
    local templates_dir="~/nuclei-templates"
    
    if [ -d "$templates_dir" ]; then
        log "Atualizando templates existentes..."
        (cd "$templates_dir" && git pull --rebase)
    else
        git clone https://github.com/projectdiscovery/nuclei-templates.git "$templates_dir"
    fi
    
    # Atualizar templates via nuclei
    if command -v nuclei &> /dev/null; then
        nuclei -update-templates
    fi
}

# Instalar Python e dependências
install_python_deps() {
    log "Instalando Python e dependências..."
    sudo apt install -y python3 python3-pip python3-venv
    pip3 install cvss-calculator
}

# Instalar wordlists
install_wordlists() {
    log "Instalando wordlists..."
    sudo apt install -y wordlists
    
    # SecLists (opcional)
    if [ ! -d "/opt/SecLists" ]; then
        sudo git clone https://github.com/danielmiessler/SecLists.git /opt/SecLists
    fi
}

# Instalar LinkFinder
install_linkfinder() {
    log "Instalando LinkFinder..."
    if [ ! -d "~/LinkFinder" ]; then
        cd ~
        git clone https://github.com/GerbenJavado/LinkFinder.git
        cd LinkFinder
        python3 -m venv ~/.venv-jsfinder
        source ~/.venv-jsfinder/bin/activate
        pip install -r requirements.txt
        deactivate
        cd -
    fi
}

# Configurar OpenPipeS com configuração interativa
setup_openpipes() {
    log "Configurando OpenPipeS..."
    
    # Criar diretório de configuração
    mkdir -p ~/.openpipes/.templates
    mkdir -p ~/.openpipes_cache
    
    # Criar config.sh com configuração interativa
    cat > ~/.openpipes/config.sh << 'EOF'
#!/bin/bash
# OpenPipeS Configuration File (Auto-generated)

# Diretórios principais
export obsdir="$HOME/.obsidianFixedMount/"
export tpdir="\$HOME/.openpipes/.templates/"
export base_dir="\$PWD"

# API Keys (configure conforme necessário)
export securitytrailskey=""
export OPENAI_API_KEY=""

# Configurações adicionais
export OPENPIPES_OBSDIR="\$obsdir"
export OPENPIPES_CONFIG_DIR="\$HOME/.openpipes"

# Cores para terminal
export red='\033[0;31m'
export green='\033[0;32m'
export yellow='\033[1;33m'
export blue='\033[0;34m'
export purple='\033[0;35m'
export cyan='\033[0;36m'
export nc='\033[0m'
EOF

    # Definir permissões seguras
    chmod 600 ~/.openpipes/config.sh
    
    # Criar arquivo de cores separado (usado por alguns scripts)
    cat > ~/colorCodes.sh << 'EOF'
#!/bin/bash
# Color codes for terminal output
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[1;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export NC='\033[0m' # No Color
EOF
    
    log "✅ Configuração criada em ~/.openpipes/"
}\$HOME/.openpipes/.templates/"
export base_dir="\$PWD"

# API Keys
export securitytrailskey=""
export OPENAI_API_KEY=""

# Cores para terminal
export red='\033[0;31m'
export green='\033[0;32m'
export yellow='\033[1;33m'
export blue='\033[0;34m'
export purple='\033[0;35m'
export cyan='\033[0;36m'
export nc='\033[0m'
EOF

    # Criar arquivo de cores
    cat > ~/colorCodes.sh << 'EOF'
#!/bin/bash
# Color codes for terminal output
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[1;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export NC='\033[0m' # No Color
EOF

    # Criar estrutura de diretórios
    mkdir -p ~/.openpipes/.templates
    mkdir -p ~/.openpipes/scripts
    mkdir -p ~/.openpipes_cache
    
    log "Configuração básica criada em ~/.openpipes/"
}

# Função principal
main() {
    echo "🚀 Instalador OpenPipeS v2.0 - Baseado no installer.sh original"
    echo "============================================================="
    
    check_sudo
    update_system
    install_system_deps
        install_go
    install_rust
    install_recon_tools
    install_amass
    install_dnsrecon
    install_web_tools
    install_python_deps
    install_wordlists
    install_linkfinder
    install_nuclei_templates
    setup_openpipes
    
    echo ""
    echo "✅ Instalação concluída com sucesso!"
    echo "===================================="
    echo "📁 Configurações salvas em: ~/.openpipes/"
    echo "🔧 Execute: source ~/.bashrc"
    echo "📖 Configure suas API keys em ~/.openpipes/config.sh"
    echo ""
    echo "🔍 Ferramentas instaladas:"
    echo "  • Amass v${AMASS_VERSION}"
    echo "  • DNSRecon v${DNSRECON_VERSION}"
    echo "  • Nuclei ${NUCLEI_VERSION}"
    echo "  • httpx, katana, feroxbuster (latest)"
    echo "  • LinkFinder (venv isolado)"
    echo ""
    echo "📋 Próximos passos:"
    echo "  1. Configure o caminho do Obsidian em ~/.openpipes/config.sh"
    echo "  2. Adicione suas API keys (OpenAI, SecurityTrails)"
    echo "  3. Execute: nuclei -update-templates"
    echo "  4. Teste: nmap -sV scanme.nmap.org"
    echo ""
    echo "🎯 OpenPipeS está pronto para uso!"
}

# Executar instalação
main
