#!/bin/bash
source $HOME/.openpipes/config.sh

for dir in "$NMAP_DIR"/nmap-*; do
    [[ ! -d "$dir" ]] && continue
    target_name="${dir##*/nmap-}"
    input_file="$dir/nuclei_urls.txt"

    if [[ ! -s "$input_file" ]]; then
        echo "[SKIP] $target_name: nuclei_urls.txt vazio ou ausente."
        continue
    fi

    # ── Tech/port-aware tags (generated by feed_nuclei) ──
    tags_file="$dir/nuclei_tags.txt"
    if [[ -s "$tags_file" ]]; then
        TAGS=$(cat "$tags_file")
    else
        TAGS="misconfig,exposure,default-login,takeover,panel,auth-bypass"
    fi
    echo "[*] Processando: $target_name (tags: $TAGS)"

    nuclei_json="$dir/nuclei_output.json"

    nuclei -l "$input_file" \
        -tags "$TAGS" \
        -pt http \
        -severity low,medium,high,critical \
        -nf \
        -timeout 5 \
        -retries 1 \
        -je "$nuclei_json"

    echo "[✔] $target_name finalizado."
done
echo "[✔] nuclei-runner concluído."
