#!/usr/bin/env python3
"""
osint_people_parser.py - People Profile Parser
Versão: 1.1 - CORRIGIDA

Parseia dados brutos de colaboradores e cria perfis individuais em Markdown.
"""

import json
import sys
import os
import logging
from pathlib import Path
from datetime import datetime
from typing import Dict, Any

# Configurar logging
logging.basicConfig(
    level=logging.INFO,
    format='[%(asctime)s] %(levelname)s: %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
log = logging.getLogger(__name__)


def sanitize_filename(name: str) -> str:
    """
    Sanitiza nome para uso como nome de arquivo.
    
    Args:
        name: Nome original
        
    Returns:
        Nome sanitizado
    """
    # Converter para lowercase e substituir caracteres inválidos
    safe = name.lower()
    safe = safe.replace(' ', '_')
    safe = ''.join(c for c in safe if c.isalnum() or c in ('_', '-'))
    
    # Remover underscores duplicados
    while '__' in safe:
        safe = safe.replace('__', '_')
    
    # Limitar tamanho
    return safe[:80]


def create_person_markdown(person: Dict[str, Any], outdir: Path) -> Path:
    """
    Cria arquivo Markdown para um perfil de pessoa.
    
    Args:
        person: Dicionário com dados da pessoa
        outdir: Diretório de saída
        
    Returns:
        Path do arquivo criado
    """
    # Extrair dados com fallbacks
    name = person.get('name', 'Unknown')
    email = person.get('email', '')
    role = person.get('role', '')
    photo = person.get('photo', '')
    github = person.get('github', '')
    linkedin = person.get('linkedin', '')
    source = person.get('source', '')
    
    # Criar nome de arquivo seguro
    safe_name = sanitize_filename(name)
    filepath = outdir / f"people_{safe_name}.md"
    
    # Verificar se já existe
    if filepath.exists():
        log.warning(f"File already exists, overwriting: {filepath}")
    
    # Criar conteúdo do arquivo
    content = f"""---
name: "{name}"
email: "{email}"
role: "{role}"
photo: "{photo}"
github: "{github}"
linkedin: "{linkedin}"
source: "{source}"
generated: "{datetime.utcnow().isoformat()}Z"
verified: false
---

# {name}

**Role:** {role}  
**Email:** {email}  
**Source:** {source}

## 🔗 Links

{f'- **GitHub:** [{github}]({github})' if github else ''}
{f'- **LinkedIn:** [{linkedin}]({linkedin})' if linkedin else ''}

## 📝 Notes

*Add your investigation notes here*

## 📂 Evidence

*Evidence will be linked here automatically*

## 🔍 Additional Information

### Timeline

- **First Seen:** {datetime.utcnow().strftime('%Y-%m-%d')}
- **Last Updated:** {datetime.utcnow().strftime('%Y-%m-%d')}

### Tags

#osint #people #investigation

---

*Generated by OPenPipeS OSINT People Module*
"""
    
    # Escrever arquivo
    try:
        with filepath.open('w', encoding='utf-8') as f:
            f.write(content)
        log.info(f"Created profile: {filepath.name}")
        return filepath
    except Exception as e:
        log.error(f"Failed to create profile for {name}: {e}")
        raise


def validate_json_structure(data: Dict[str, Any]) -> bool:
    """
    Valida estrutura do JSON de entrada.
    
    Args:
        data: Dados carregados do JSON
        
    Returns:
        True se válido, False caso contrário
    """
    if not isinstance(data, dict):
        log.error("JSON root must be an object")
        return False
    
    if 'people' not in data:
        log.error("JSON must contain 'people' key")
        return False
    
    if not isinstance(data['people'], list):
        log.error("'people' must be a list")
        return False
    
    return True


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <input_json> <output_dir>")
        sys.exit(1)
    
    infile = Path(sys.argv[1])
    outdir = Path(sys.argv[2])
    
    # Validar arquivo de entrada
    if not infile.exists():
        log.error(f"Input file not found: {infile}")
        sys.exit(1)
    
    # Criar diretório de saída
    outdir.mkdir(parents=True, exist_ok=True)
    
    # Carregar JSON
    try:
        with infile.open('r', encoding='utf-8') as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        log.error(f"Invalid JSON: {e}")
        sys.exit(1)
    except Exception as e:
        log.error(f"Failed to read input file: {e}")
        sys.exit(1)
    
    # Validar estrutura
    if not validate_json_structure(data):
        sys.exit(1)
    
    people = data['people']
    log.info(f"Processing {len(people)} people...")
    
    # Processar cada pessoa
    created_files = []
    errors = 0
    
    for idx, person in enumerate(people, 1):
        try:
            filepath = create_person_markdown(person, outdir)
            created_files.append(filepath)
        except Exception as e:
            log.error(f"Failed to process person #{idx}: {e}")
            errors += 1
    
    # Resumo
    log.info(f"[✔] Parser completed!")
    log.info(f"Total people: {len(people)}")
    log.info(f"Profiles created: {len(created_files)}")
    log.info(f"Errors: {errors}")
    
    # Criar arquivo de índice
    index_file = outdir / '_index.md'
    
    with index_file.open('w', encoding='utf-8') as f:
        f.write(f"# People Index\n\n")
        f.write(f"**Generated:** {datetime.utcnow().isoformat()}Z\n")
        f.write(f"**Total Profiles:** {len(created_files)}\n\n")
        f.write("## Profiles\n\n")
        
        for filepath in sorted(created_files):
            f.write(f"- [[{filepath.name}]]\n")
    
    log.info(f"Index created: {index_file}")


if __name__ == '__main__':
    main()